export const BOTTOM_DRAWER_KEYS = {
  confirm: "confirm",
  uploadMedia: "uploadMedia",
  customSelectList: "customSelectList",
  flatSelectList: "flatSelectList",
  workSetSelectList: "workSetSelectList",
  materialActions: "materialActions",
  documentActions: "documentActions",
  paymentActions: "paymentActions",
  stagesActions: "stagesActions",
  signatoriesList: "signatoriesList",
  datePicker: "datePicker",
  pointInfo: "pointInfo",
  citySelect: "citySelect",
} as const;
